### ISSUE TITLE
Detailed installation instructions 

### ISSUE THREAD

**Issue by misterhsp** [jackyzy823/fxa-selfhosting#10]
Detailed installation instructions would be good. According to the README, most will probably not be able to do that. I count myself among them.

...

**Comment by jackyzy823** [comment]
I have updated README file and make instruction a bit clear. I hope this will help you.

**Comment by jackyzy823** [comment]
Well. Self hosting is not a simple thing let alone self hosting all fxa stack. If you feel this too complex, you could use mozilla's ones. If you concern about your data , you can self host sync server and use mozilla's account system.
