### ISSUE TITLE
Can't connect to channelserver

### ISSUE THREAD

**Issue by alnmy** [jackyzy823/fxa-selfhosting#16]
I modified the dockerfile for channelserver to use 
mozilla/channelserver@sha256:01f9251637cc3679b8cf31493569a79a27b41f952d4eb3d5306e1ee8d9d3feea

When I try use the www.fxa login on another device, in the logs I get:
`WebChannel error: No Such Channel` in the console log.

Essentially, I cannot add the FxA server to other devices after I added one because channelserver is failing. 

Channelserver has these logs (repeats for a bit longer):
```channelserver_1                     | {"Logger":"channelserver-1.0.0","Type":"channelserver:log","Pid":1,"Severity":6,"Timestamp":1675526094669924741,"Fields":{"msg":"Establishing connection to Stat Server","port":"8125","server":"localhost"}}
channelserver_1                     | {"Logger":"channelserver-1.0.0","Type":"channelserver:log","Pid":1,"Severity":7,"Timestamp":1675526094669937662,"Fields":{"msg":"Starting server: \"0.0.0.0:8000\""}}
channelserver_1                     | {"Logger":"channelserver-1.0.0","Type":"channelserver:log","Pid":1,"Severity":6,"Timestamp":1675526094719605325,"Fields":{"msg":"Establishing connection to Stat Server","port":"8125","server":"localhost"}}
channelserver_1                     | {"Logger":"channelserver-1.0.0","Type":"channelserver:log","Pid":1,"Severity":6,"Timestamp":1675526094805945007,"Fields":{"msg":"Establishing connection to Stat Server","port":"8125","server":"localhost"}}
channelserver_1                     | {"Logger":"channelserver-1.0.0","Type":"channelserver:log","Pid":1,"Severity":6,"Timestamp":1675526094859267084,"Fields":{"msg":"Establishing connection to Stat Server","port":"8125","server":"localhost"}}
```

My config: 
https://pastebin.com/EUPrVsEg

Nginx config:
https://pastebin.com/raw/j1xYa7Ti

**Comment by jackyzy823** [comment]
The channel server part is not well tested because i do not use that :(   .

Some more details are very helpful.

1. Have you tried to use mozilla's channelserver and check if it works ?

2. Have you configured the mobile device  to custom account/sync url before you scan the QR code?


> `WebChannel error: No Such Channel` in the console log.

This may not be related to channel service. it may be a bridge between fxa Web UI and browser part of fxa account system.

**Comment by alnmy** [comment]
> The channel server part is not well tested because i do not use that :( .
> 
> Some more details are very helpful.
> 
>     1. Have you tried to use mozilla's channelserver and check if it works ?
> 
>     2. Have you configured the mobile device  to custom account/sync url before you scan the QR code?
> 
> 
> > `WebChannel error: No Such Channel` in the console log.
> 
> This may not be related to channel service. it may be a bridge between fxa Web UI and browser part of fxa account system.

Hello, the original issue has gone away even though I have done nothing since then, and I am not quite sure what caused it. 
However, now I have a new issue on the mobile device given when I try to pair with the QR code or logging in normally. 
![image](https://user-images.githubusercontent.com/67667676/216840728-0443ed32-904b-4c1a-9663-1e2a3dee57e8.png)
I am using Firefox for iOS.

**Comment by jackyzy823** [comment]
[The commit](https://github.com/jackyzy823/fxa-selfhosting/commit/f4bc50738b294a38f6b6169a0c30b70eac8cee2c) which fixes this issue is in develop branch , just not been migrated yet.

You can add these lines to `_init/auth/oauthserver-prod.tmpl.yml` and re-run ./init.sh to update the config and then restart servers.

**Comment by alnmy** [comment]
Thanks very much for the help, all related issues now seem to be solved.
