### ISSUE TITLE
waitforintra incorrect depend

### ISSUE THREAD

**Issue by hockeymikey** [jackyzy823/fxa-selfhosting#22]
https://github.com/jackyzy823/fxa-selfhosting/blob/a942565550805540e333a4fcce1921e963e40d9d/docker-compose.tmpl.yml#L67C9-L67C11

I think this is supposed to be mysqldb, not db.

**Comment by jackyzy823** [comment]
Sorry for that. I updated a commit , could you help to verify if it fixes. Thanks.

**Comment by hockeymikey** [comment]
@jackyzy823 Not a problem, works on my end. Thank you so much for putting this together, such an amazing project.
