### ISSUE TITLE
Problem when sending email, does fxa smtp follow the protocol correctly

### ISSUE THREAD

**Issue by Dataaja95** [jackyzy823/fxa-selfhosting#23]
hi
I have defined the fxa configuration file as the mail sender type 3rd, the username, password and other server information are correct, the port I use is 587, but I get such an error message in the logs of my postfix server, it would seem that fxa does not follow the smtp protocol, or is it a programming error
.
server postfix/submission/smtpd[6987]: connect from xxxxxxxxx[xxxxxxx]\n2024-04-09T08:45:36.913314+03:00 server postfix/submission/smtpd[6987]: improper command pipelining after CONNECT from xxxxxxx[xxxxxxx]: \\026\\003\\001\\001u\\001\\000\\001q\\003\\003H\\373\\v\\205\\200*\\207\\024\\301\\267\\236LV\\244\\232\\255i\\224R\\361Q\\311\\036J\\v\\033\\257\\3357\\330-) ,m\\260Rh^d\\027\\001W}\\366)\\320\\032\\252\\247Vvg\\251\\254\\226\\v\\004\\337\\353\\326g8\\254\\277\\000v\\023\\002\\023\\003\\023\\001\\300/\\300+\\3000\\300,\\000\\236\\300'\\000g\\300(\n2024-04-09T08:45:36.926912+03:00 server postfix/submission/smtpd[6987]: lost connection after CONNECT from xxxxxxx[xxxxxx]\n2024-04-09T08:45:36.927369+03:00 server postfix/submission/smtpd[6987]: disconnect from xxxxxx[xxxxxx] commands=0/0",

**Comment by jackyzy823** [comment]
Hello, i don't use 3rd sender. 

So just a guess:  Did you set smtp_secure to `true` , but your sender doesn't support at port 587 (ie it talks plain SMTP protocol , not over tls) ?

**Comment by Dataaja95** [comment]
smtp_secure is true and the port is 587, does fxa accept directly
contact the mail server or does it use postfix which is installed on the machine where fxa is installed which should i use if i don't use 3rd as send type.

**Comment by jackyzy823** [comment]
If your machine has sending email permission( most cloud provider requires opening a support ticket to allow machine to send email outgoing) ,you could use "localrelay" type ( this type bundled a exim4 to send email for you)

If you just want to use fxa stack yourself , you could just use "localhelper" type.

**Comment by Dataaja95** [comment]
So how does localhelper work, do I specify the port, hostname and others
the data normally for the fxa configuration, what about localrelay, it installs exim as a docker container, how do I configure the data for it, what if I use starttls on my server, how do I then configure fxa
@jackyzy823

**Comment by Dataaja95** [comment]
localhelper seems to work, I get a notification about sending an email when creating a user account, but no email
never figure out how to configure localhelper with the correct email server settings

**Comment by jackyzy823** [comment]
> localhelper seems to work, I get a notification about sending an email when creating a user account, but no email
never figure out how to configure localhelper with the correct email server settings

Please refer to the output of the ./init.sh , it tells you how to get your verify code from localhelper.

You could 
1)  https://github.com/jackyzy823/fxa-selfhosting/blob/bdfa323fc33d6142af0904bdb4af63b61db012c8/init.sh#L181

2) https://github.com/jackyzy823/fxa-selfhosting/blob/bdfa323fc33d6142af0904bdb4af63b61db012c8/init.sh#L189-L192

**Comment by Dataaja95** [comment]
Thanks, I got the system working using localhelper,
  I'm closing this the problem

**Comment by Dataaja95** [comment]
Now Firefox is connected to the server, but the account manager in Firefox's sync settings doesn't seem to work, when I open it, I get an error
General application error

Something went wrong. Please try again later.

Is this normal operation and that user interface has just not been implemented.
@jackyzy823

**Comment by jackyzy823** [comment]
Please post your config, the screenshot of error and if possible the console output from devtool (F12) of browser.

**Comment by jackyzy823** [comment]
I mean error log / failed request  from devtool console . ( Not these css code)

And v1.247.2 is quite old version Is there any reason that you choose this version?

**Comment by Dataaja95** [comment]
How can I upgrade to the latest version by downloading the changes with the command git pull in the configuration file
  the same old version is displayed. There is NO reason for me to use this old version
@jackyzy823

**Comment by jackyzy823** [comment]
1) git pull to the latest version. 
2) cp the latest version `config.yml.sample` to `config.yml`
3) edit `config.yml` to customize
4) execute ./init.sh

**Comment by Dataaja95** [comment]
I updated to the latest version, now account management doesn't open, but keeps downloading endlessly, etc
attached conf and a screenshot from the window, error report from the Firefox developer console below
![Screenshot 2024-04-11 at 10-29-25 Mozilla accounts](https://github.com/jackyzy823/fxa-selfhosting/assets/166509418/934174c5-63ca-4a29-b441-5639a2d95b90)

[config.txt](https://github.com/jackyzy823/fxa-selfhosting/files/14942988/config.txt)

No Sentry dsn provided main.c641f4a6.js:2:523890
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://syncgraphql.domain.local/graphql. (Reason: CORS request did not succeed). Status code: (null). 2
networkError TypeError: NetworkError when attempting to fetch resource. main.c641f4a6.js:2:311024
networkError TypeError: NetworkError when attempting to fetch resource. main.c641f4a6.js:2:311024
(Glean.core.Pings.Maker) Storage for deletion-request empty. Ping will still be sent. main.c641f4a6.js:2:1180483
(Glean.core.Upload.PingUploadManager) Ping 6ee2d6f8-bd41-4084-8383-654532569fdb successfully sent 200. main.c641f4a6.js:2:1180483
Download the Apollo DevTools for a better development experience: https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/ main.c641f4a6.js:2:1122658

@jackyzy823

**Comment by jackyzy823** [comment]
It looks like CORS issue?

Could you post the request header / response from the request "OPTIONS https://syncgraphql.domain.local/graphql" in "Network" section of devtool.

**Comment by Dataaja95** [comment]
The problem was solved, it was a dns configuration error domain
syncgraphql.domain.local was not added to the network dns server or the hosts file of the workstation, now everything works, thanks for the great project and keep up the good work
@jackyzy823

**Comment by Handrail9** [comment]
@jackyzy823 I wanted to pop in to let you know that it appears that if smtp_secure is true then the only port that it will log into is 465. Port 587 does not seem to work.

**Comment by jackyzy823** [comment]
Hi @Handrail9 , fxa use nodemailer to send mail. according to the docs https://nodemailer.com/smtp/ ,  this might be the expected behavior.

> port – is the port to connect to (defaults to 587 if is secure is false or 465 if true)


> secure – if true the connection will use TLS when connecting to server. If false (the default) then TLS is used if server supports the STARTTLS extension. In most cases set this value to true if you are connecting to port 465. For port 587 or 25 keep it false
