### ISSUE TITLE
sin up with own oauth

### ISSUE THREAD

**Issue by lbouquinUniv** [jackyzy823/fxa-selfhosting#3]
Hi, 
We wants connect ownauthentication system in fxa to  sin up   and sin in  service.  How we can do that.

**Comment by jackyzy823** [comment]
Sorry. I think there's no way to use other authentication system to sign in/up in fxa.

**Comment by lbouquinUniv** [comment]
Thanks.
 Just one last question ?  It's possible to filter domain address ?

**Comment by jackyzy823** [comment]
Previous discussion in https://github.com/mozilla/fxa/issues/3652#issuecomment-602542246

> > c) But it can be that other users use my personal FXA/sync server to sync their browsers? Can the server locked down somehow? Like HTTP Basic auth, and the user/pass is added to the URL like https://user:pass@www.fxa.example.org Would the browser still sync in this case?
> 
> since mozllia use fxa as a public service, i dont think they designed a principal to forbid some email addresses to register.
> 
> So the only way i found is to configure your email sender to only send mails to allowed domains which makes that user can not proceed the verfication step and can not using sync service.
