### ISSUE TITLE
Create user using command line?

### ISSUE THREAD

**Issue by omnicortex** [jackyzy823/fxa-selfhosting#32]
I am running fxa on my local machine offline and have no email to give to FxA. Is there a way to create a user from command line or programmatically? I need to bypass email verification.

**Comment by jackyzy823** [comment]
Hello, you don't really need a valid email.  

if you set mail.type to localhelper , you could get activate code from `docker-compose logs fxa-auth-local-mail-helper |grep -i code` or `curl http://$localhelperweb/mail/<name_part_before_at_mark>`

Also you could create account programmatically  via https://github.com/mozilla/PyFxA , however you still need to activate the account.

**Comment by omnicortex** [comment]
Thanks. I was able to get the activation code.  I wish there is a way to disable this activation code requirement.
